//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Store.PartnerCenter.Storefront
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string CreationDate { get; set; }
        public string ExpiryDate { get; set; }
        public string SubcriptionFriendlyName { get; set; }
        public string OfferName { get; set; }
        public string PartnerCenterOrderId { get; set; }
        public string ChargeType { get; set; }
        public string UnitPrice { get; set; }
        public string Quantity { get; set; }
        public string PreTaxTotal { get; set; }
        public string AfterTaxTotal { get; set; }
        public string InvoiceNumber { get; set; }
    }
}
